# Generated by Django 3.2 on 2022-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1)),
                ('category', models.ManyToManyField(to='pass_things.Category')),
            ],
        ),
    ]
